Repository heading1/WYLSBingsu, pull requests merged in 2022-06, with the labels that each got.

#26 Feature/#18
  .gitignore
  server/index.ts
  server/package-lock.json
  server/package.json
  server/src/db/models/.gitkeep
  server/src/db/schemas/.gitkeep
  server/src/middlewares/.gitkeep
  server/src/routers/.gitkeep
  server/src/services/.gitkeep
  server/tests/.gitkeep
Labels: ⚙️ Backend, ↔️ mid-priority

#28 feature/#19
  client/babel.config.json
  client/library/Bingact.js
  client/library/Hooks.js
  client/library/index.js
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/index.js
  client/webpack.config.js
Labels: 🖥 Frontend, ❗️high-priority, 🔩 setup

#31 feature/#30 라이브러리 dependencies추가
  server/package-lock.json
  server/package.json
Labels: ⚙️ Backend, 🔩 setup

#33 feature/#22 ESLint, Prettier 설정
  .eslintrc
  .prettierrc
Labels: ⚙️ Backend, 🖥 Frontend, ❗️high-priority, 🔩 setup

#36 feature/#35 스키마 셋팅
  server/src/db/schemas/article-schema.ts
  server/src/db/schemas/user-schema.ts
Labels: ⚙️ Backend, 🖥 Frontend, ❗️high-priority, 🔩 setup

#39 feature/#38 app 구동 셋팅
  server/index.ts
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/db/schemas/.gitkeep
  server/tsconfig.json
  server/types/express/index.d.ts
Labels: ⚙️ Backend, ❗️high-priority, 🔩 setup

#42 feature/#41 React로 전환
  client/babel.config.json
  client/library/index.js
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/App.tsx
  client/src/index.js
  client/src/index.tsx
  client/tsconfig.json
  client/webpack.config.js
Labels: 🖥 Frontend, ❗️high-priority, 🔩 setup

#47 feature/#46 이슈 자동 닫힘 테스트
  server/package-lock.json
Labels: ⚙️ Backend, 🖥 Frontend, 🔧 enhancement

#49 feature/#48 폴더 이름 수정
  server/src/db/schemas/ArticleSchema.ts
  server/src/db/schemas/UserSchema.ts
Labels: 🐛 Bug, ⚙️ Backend

#50 feature/#43 전역 스타일 설정
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/pull_request_template.md
  client/src/index.tsx
  client/src/styles/GlobalStyle.tsx
  client/src/styles/Theme.tsx
  client/src/styles/index.tsx
Labels: 🖥 Frontend, ❗️high-priority, 🔨 Feature

#52 feature/#37 로그인화면 기본 디자인 완성, validation
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/pages/index.tsx
  client/src/pages/login-page/LoginPage.tsx
  client/src/pages/login-page/LoginPageStyle.tsx
  client/src/pages/login-page/components/LoginForm.tsx
  client/src/pages/login-page/components/LoginFormStyle.tsx
  client/src/pages/login-page/index.tsx
  client/src/styles/GlobalStyle.tsx
  client/src/styles/Theme.tsx
  client/src/styles/styled.d.ts
  client/webpack.config.js
Labels: 🖥 Frontend, ❗️high-priority, 🔨 Feature

#55 feature/#54 Github OAuth 스켈레톤 버튼
  client/src/pages/login-page/components/GithubOAuth.tsx
  client/src/pages/login-page/components/GithubOAuthStyle.tsx
  client/src/pages/login-page/components/LoginForm.tsx
  client/src/pages/login-page/components/LoginFormStyle.tsx
Labels: 🖥 Frontend, ❗️high-priority, 🔨 Feature

#56 Feature/#53 메인페이지 레이아웃
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/assets/images/bingsu.jpeg
  client/src/assets/images/riceCake.png
  client/src/pages/index.tsx
  client/src/pages/main-page/MainPage.tsx
  client/src/pages/main-page/MainPageStyle.tsx
  client/src/pages/main-page/components/Footer.tsx
  client/src/pages/main-page/components/FooterStyle.tsx
  client/src/pages/main-page/components/Header.tsx
  client/src/pages/main-page/components/HeaderStyle.tsx
  client/src/pages/main-page/components/Main.tsx
  client/src/pages/main-page/components/MainStyle.tsx
  client/src/pages/main-page/components/index.tsx
  client/src/pages/main-page/index.tsx
  client/src/types/images.d.ts
  client/tsconfig.json
  client/webpack.config.js
Labels: 🖥 Frontend, ❗️high-priority, 🔨 Feature

#58 feature/#57 회원가입 페이지 기초 디자인
  client/src/App.tsx
  client/src/common/form-component/CustomForm.tsx
  client/src/common/form-component/CustomFormStyle.tsx
  client/src/pages/index.tsx
  client/src/pages/login-page/LoginPage.tsx
  client/src/pages/login-page/LoginPageStyle.tsx
  client/src/pages/login-page/components/LoginForm.tsx
  client/src/pages/register-page/RegisterPage.tsx
  client/src/pages/register-page/RegisterPageStyle.tsx
  client/src/pages/register-page/components/RegisterForm.tsx
  client/src/pages/register-page/index.ts
  client/src/types/types.ts
  client/tsconfig.json
  client/webpack.config.js
Labels: 🖥 Frontend, ❗️high-priority, 🔨 Feature

#64 feature/#59 Email 인증 코드 입력 컴포넌트
  client/src/common/form-component/CustomForm.tsx
  client/src/common/form-component/CustomFormStyle.tsx
  client/src/pages/login-page/components/LoginForm.tsx
  client/src/pages/login-page/components/LoginFormStyle.tsx
  client/src/pages/register-page/RegisterPage.tsx
  client/src/pages/register-page/RegisterPageStyle.tsx
  client/src/pages/register-page/components/EmailCertificationForm.tsx
  client/src/pages/register-page/components/EmailCertificationFormStyle.tsx
  client/src/pages/register-page/components/RegisterForm.tsx
  client/src/pages/register-page/components/RegisterFormStyle.tsx
Labels: 🖥 Frontend, 🔨 Feature, ↔️ mid-priority

#66 feature/#65 스키마 세팅
  server/src/db/schemas/AuthNumberSchema.ts
Labels: ⚙️ Backend, ↔️ mid-priority, 🔩 setup

#62 feature/#61 자동배포를 위한 yml 구성
  .github/workflows/main.yml
Labels: ⚙️ Backend, 🔨 Feature, ↔️ mid-priority

#69 feature/#68 에러 페이지 컴포넌트 생성 및 라우팅
  .github/pull_request_template.md
  client/src/App.tsx
  client/src/pages/error-page/ErrorPage.tsx
  client/src/pages/error-page/index.ts
  client/src/pages/index.tsx
  client/src/types/styled.d.ts
Labels: 🖥 Frontend, ❗️high-priority, 🔨 Feature

#71 feature/#67 회원가입 API
  server/src/app.ts
  server/src/db/index.ts
  server/src/db/models/.gitkeep
  server/src/db/models/UserModel.ts
  server/src/routers/.gitkeep
  server/src/routers/UserRouter.ts
  server/src/routers/index.ts
  server/src/services/.gitkeep
  server/src/services/UserService.ts
  server/src/services/index.ts
Labels: ⚙️ Backend, ❗️high-priority, 🔨 Feature

#72 Feature/#63 내용쓰기 모델,서비스,라우터 추가
  server/index.ts
  server/src/db/index.ts
  server/src/db/models/ArticleModel.ts
  server/src/db/models/UserModel.ts
  server/src/routers/ArticleRouter.ts
  server/src/routers/index.ts
  server/src/services/ArticleService.ts
  server/src/services/index.ts
Labels: 🐛 Bug, ⚙️ Backend, ❗️high-priority, 🔨 Feature

#77 feature/#70 오류 페이지 기초 디자인 구성
  client/src/assets/images/no_bingsu.jpeg
  client/src/assets/images/only_bingsu.png
  client/src/common/hooks/useDeviceViewport.tsx
  client/src/pages/error-page/ErrorPage.tsx
  client/src/pages/error-page/ErrorPageStyle.tsx
  client/src/types/interfaces.ts
Labels: 🖥 Frontend, ❗️high-priority, 🔨 Feature

#81 Feature/#78 로딩컴포넌트 생성
  client/src/components/Loading.tsx
Labels: 🖥 Frontend, 🔨 Feature, ↔️ mid-priority

#85 feature/#80 랜덤 유저 방문 API 구현
  server/src/db/models/UserModel.ts
  server/src/routers/UserRouter.ts
  server/src/services/UserService.ts
Labels: ⚙️ Backend, ❗️high-priority, 🔨 Feature

#87 Feature/#86토핑 이미지 변경
  client/src/assets/images/chocolate1.png
  client/src/assets/images/chocolate2.png
  client/src/assets/images/chocolate3.png
  client/src/assets/images/chocolate4.png
  client/src/assets/images/index.tsx
  client/src/assets/images/kiwi.png
  client/src/assets/images/pineapple.png
  client/src/assets/images/watermelon.png
  client/src/pages/main-page/MainPage.tsx
  client/src/pages/main-page/components/Topping.tsx
Labels: 🖥 Frontend, ❗️high-priority, 🔧 enhancement

#90 Feature/#83 로그인 API 구현
  server/package-lock.json
  server/package.json
  server/src/db/models/UserModel.ts
  server/src/db/schemas/UserSchema.ts
  server/src/middlewares/.gitkeep
  server/src/middlewares/AuthJWT.ts
  server/src/middlewares/index.ts
  server/src/routers/UserRouter.ts
  server/src/services/UserService.ts
Labels: ⚙️ Backend, ❗️high-priority, 🔨 Feature

#91 feature/#88 글쓰기 form 완성
  client/src/App.tsx
  client/src/common/hooks/useDeviceViewport.tsx
  client/src/pages/index.tsx
  client/src/pages/write-page/WritePage.tsx
  client/src/pages/write-page/WritePageStyle.tsx
  client/src/pages/write-page/components/ArticleForm.tsx
  client/src/pages/write-page/components/ArticleFormStyle.tsx
  client/src/pages/write-page/index.ts
  client/src/styles/GlobalStyle.tsx
Labels: 🖥 Frontend, ❗️high-priority, 🔨 Feature

#96 feature/#95 회원가입 API 오타 수정
  server/src/middlewares/AuthJWT.ts
  server/src/services/UserService.ts
Labels: 🐛 Bug, ⚙️ Backend, ❗️high-priority

#97 feature/#92 공유링크 생성
  server/src/middlewares/AuthJWT.ts
  server/src/routers/UserRouter.ts
  server/src/services/UserService.ts
  server/tsconfig.json
  server/types/express/index.d.ts
Labels: ⚙️ Backend, ❗️high-priority, 🔨 Feature

#99 feature/#98 유저정보수정
  server/src/db/models/UserModel.ts
  server/src/middlewares/TokenRequestMatch.ts
  server/src/middlewares/index.ts
  server/src/routers/UserRouter.ts
  server/src/services/UserService.ts
Labels: ⚙️ Backend, ❗️high-priority, 🔨 Feature

#101 feature/#100 토큰 전달 방식 변경-쿠키사용
  server/src/routers/UserRouter.ts
  server/src/services/UserService.ts
Labels: ⚙️ Backend, ❗️high-priority, 🔧 enhancement

#104 feature/#102
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/middlewares/AuthJWT.ts
  server/src/middlewares/ErrorHandler.ts
  server/src/middlewares/ErrorLogger.ts
  server/src/middlewares/TokenRequestMatch.ts
  server/src/middlewares/index.ts
Labels: ⚙️ Backend, ❗️high-priority, 🔧 enhancement

#108 feature/#94 로그인 요청 후 토큰 저장
  client/src/common/form-component/CustomForm.tsx
  client/src/common/form-component/CustomFormStyle.tsx
  client/src/pages/login-page/components/LoginForm.tsx
  client/src/pages/login-page/components/LoginFormStyle.tsx
  client/src/pages/login-page/hook/useLogin.ts
  server/src/app.ts
Labels: 🖥 Frontend, ❗️high-priority, 🔨 Feature

#107 feature/#105 회원탈퇴API 구현
  server/src/db/models/UserModel.ts
  server/src/routers/UserRouter.ts
  server/src/services/UserService.ts
Labels: ⚙️ Backend, ❗️high-priority, 🔨 Feature, 🔧 enhancement

#112 feature/#111 로딩 컴포넌트 배경 블러처리
  client/src/components/Loading.tsx
  client/src/pages/main-page/MainPageStyle.tsx
Labels: 🖥 Frontend, 🔨 Feature, ↔️ mid-priority, 🔧 enhancement

#106 feature/#103 글쓰기 로직 빠진 것 추가
  server/src/app.ts
  server/src/db/schemas/ArticleSchema.ts
  server/src/routers/ArticleRouter.ts
Labels: 🐛 Bug, ⚙️ Backend, 🔨 Feature

#113 feature/#89 토핑 상세보기 구현
  client/src/pages/main-page/MainPage.tsx
  client/src/pages/main-page/components/ArticleForm.tsx
  client/src/pages/main-page/components/ArticleFormStyle.tsx
  client/src/pages/main-page/components/Detail.tsx
  client/src/pages/main-page/components/DetailStyle.tsx
Labels: 🖥 Frontend, ❗️high-priority, 🔨 Feature

#115 feature/#93 이메일 인증
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/db/index.ts
  server/src/db/models/AuthNumberModel.ts
  server/src/db/schemas/AuthNumberSchema.ts
  server/src/routers/UserRouter.ts
  server/src/services/AuthNumberService.ts
  server/src/services/MailService.ts
  server/src/services/index.ts
Labels: ⚙️ Backend, ❗️high-priority, 🔨 Feature

#118 feature/#117 토핑 클릭이벤트
  client/src/common/components/Loading.tsx
  client/src/pages/login-page/components/LoginForm.tsx
  client/src/pages/main-page/MainPage.tsx
  client/src/pages/main-page/MainPageStyle.tsx
  client/src/pages/main-page/components/ArticleForm.tsx
  client/src/pages/main-page/components/Detail.tsx
Labels: 🖥 Frontend, 🔨 Feature, ↔️ mid-priority

#120 feature/#109 회원가입 POST 요청
  client/src/common/form-component/CustomForm.tsx
  client/src/common/form-component/CustomFormStyle.tsx
  client/src/common/util/generateRandomName.ts
  client/src/common/util/name.json
  client/src/pages/login-page/components/LoginForm.tsx
  client/src/pages/login-page/hook/useLogin.ts
  client/src/pages/register-page/RegisterPage.tsx
  client/src/pages/register-page/components/EmailCertificationForm.tsx
  client/src/pages/register-page/components/EmailCertificationFormStyle.tsx
  client/src/pages/register-page/components/RegisterForm.tsx
  client/src/pages/register-page/components/RegisterFormStyle.tsx
  client/src/pages/register-page/hook/useRegister.ts
  client/src/types/interfaces.ts
  client/src/types/types.ts
Labels: 🖥 Frontend, ❗️high-priority, 🔨 Feature

#129 feature/#128 CustomForm 디렉토리 이동
  client/src/common/components/form-component/CustomForm.tsx
  client/src/common/components/form-component/CustomFormStyle.tsx
  client/src/pages/login-page/components/LoginForm.tsx
  client/src/pages/register-page/components/RegisterForm.tsx
Labels: 🖥 Frontend, ⬇️ low-priority, 🔧 enhancement

#127 feature/#119 회원가입 API 수정
  server/src/db/models/AuthNumberModel.ts
  server/src/db/schemas/AuthNumberSchema.ts
  server/src/routers/UserRouter.ts
  server/src/services/AuthNumberService.ts
Labels: ⚙️ Backend, ❗️high-priority, 🔨 Feature, 🔧 enhancement

#130 feature/#124 모바일환경 적용
  client/src/assets/images/index.tsx
  client/src/pages/main-page/MainPage.tsx
  client/src/pages/main-page/MainPageStyle.tsx
  client/src/pages/main-page/components/Header.tsx
  client/src/pages/main-page/components/index.tsx
Labels: 🖥 Frontend, ↔️ mid-priority, 🔧 enhancement

#133 feature#131 access/Refresh 토큰 미들웨어 수정
  server/src/middlewares/AuthJWT.ts
Labels: 🐛 Bug, ⚙️ Backend, ❗️high-priority

#134 Feature/#132 알림 컴포넌트
  client/src/common/components/Modal.tsx
  client/src/pages/main-page/MainPage.tsx
Labels: 🖥 Frontend, ❗️high-priority, 🔨 Feature

#136 feature#135 이메일 인증 API구현
  server/src/routers/UserRouter.ts
Labels: ⚙️ Backend, 🔨 Feature, ↔️ mid-priority

#137 feature/#114 페이지네이션 추가
  server/src/db/models/ArticleModel.ts
  server/src/routers/ArticleRouter.ts
  server/src/services/ArticleService.ts
Labels: ⚙️ Backend, ❗️high-priority, 🔨 Feature

#140 feature/#123 공유하기 기능
  client/src/common/components/Modal.tsx
  client/src/common/utils/generateRandomName.ts
  client/src/common/utils/name.json
  client/src/pages/main-page/MainPage.tsx
  client/src/pages/main-page/components/Header.tsx
  client/src/pages/main-page/hooks/useShareMyLink.tsx
  client/src/pages/register-page/components/EmailCertificationForm.tsx
Labels: 🖥 Frontend, ❗️high-priority, 🔨 Feature

#142 feature/#139 비밀번호 찾기 API구현
  server/src/routers/UserRouter.ts
  server/src/services/MailService.ts
  server/src/services/UserService.ts
Labels: ⚙️ Backend, ❗️high-priority, 🔨 Feature

#144 Feature/#138 디테일 API
  server/src/db/models/ArticleModel.ts
  server/src/routers/ArticleRouter.ts
  server/src/services/ArticleService.ts
Labels: ⚙️ Backend, ❗️high-priority, 🔨 Feature

#151 feature/#150 로그인시 성공시 클라이언트에 userId값 전달추가
  server/src/routers/UserRouter.ts
  server/src/services/UserService.ts
Labels: ⚙️ Backend, ❗️high-priority, 🔧 enhancement

#152 feature/#121 feat: 토핑 페이지네이션
  client/src/App.tsx
  client/src/pages/main-page/MainPage.tsx
  client/src/pages/main-page/components/ArticleForm.tsx
  client/src/pages/main-page/components/Detail.tsx
  client/src/pages/main-page/hooks/useDidMountEffect.tsx
  client/src/pages/main-page/hooks/useShareMyLink.tsx
  client/src/pages/main-page/hooks/useToppingDetail.tsx
  client/src/pages/main-page/hooks/useToppingList.tsx
Labels: 🖥 Frontend, ❗️high-priority, 🔨 Feature

#154 Feature/#149 JWT 토큰 값에 _ID값 추가 및 그에 따른 수정
  server/src/middlewares/AuthJWT.ts
  server/src/routers/ArticleRouter.ts
  server/src/services/UserService.ts
Labels: ⚙️ Backend, ❗️high-priority, 🔧 enhancement

#153 feature/#122 내 빙수가기 기능
  client/src/pages/main-page/MainPage.tsx
  client/src/pages/main-page/components/Header.tsx
Labels: 🖥 Frontend, ❗️high-priority, 🔨 Feature
