Repository heading1/WYLSBingsu, pull requests merged in 2022-07, with the labels that each got.

#163 feature/#160 비밀번호 분실 flag값 email -> password수정
  server/src/routers/UserRouter.ts
Labels: 🐛 Bug, ⚙️ Backend, ⬇️ low-priority

#164 feature/#146 글쓰기 POST 훅 구현
  client/src/common/components/response-modal/ResponseModal.tsx
  client/src/common/components/response-modal/ResponseModalStyle.tsx
  client/src/pages/register-page/components/RegisterForm.tsx
  client/src/pages/write-page/WritePage.tsx
  client/src/pages/write-page/WritePageStyle.tsx
  client/src/pages/write-page/components/ArticleForm.tsx
  client/src/pages/write-page/components/ArticleFormStyle.tsx
  client/src/pages/write-page/components/SelectTopingStyle.tsx
  client/src/pages/write-page/components/SelectTopping.tsx
  client/src/pages/write-page/components/StateButton.tsx
  client/src/pages/write-page/hook/useWrite.ts
  client/src/types/interfaces.ts
  client/src/types/router.d.ts
Labels: 🖥 Frontend, ❗️high-priority, 🔨 Feature

#166 feature/#165 로그인 성공 시 유저 빙수로 이동
  client/src/pages/login-page/hook/useLogin.ts
Labels: 🖥 Frontend, ❗️high-priority, 🔨 Feature

#170 feature/#167 로그인 정보 가져오기 API 구현
  server/src/routers/UserRouter.ts
Labels: ⚙️ Backend, 🔨 Feature, ↔️ mid-priority

#171 feature/#169 상세페이지 분기점 수정
  server/src/db/models/ArticleModel.ts
  server/src/routers/ArticleRouter.ts
  server/src/services/ArticleService.ts
Labels: 🐛 Bug, ⚙️ Backend, ❗️high-priority

#172 feature/#167 빙수주인 닉네임 가져오기 API 구현
  server/src/db/models/UserModel.ts
  server/src/routers/UserRouter.ts
  server/src/services/UserService.ts
Labels: ⚙️ Backend, ↔️ mid-priority, 🔧 enhancement

#173 Feature/#162 UI/UX수정
  client/src/App.tsx
  client/src/pages/main-page/MainPage.tsx
  client/src/pages/main-page/components/Footer.tsx
  client/src/pages/main-page/components/FooterStyle.tsx
  client/src/pages/main-page/components/Header.tsx
  client/src/pages/main-page/components/HeaderStyle.tsx
  client/src/pages/main-page/hooks/useInfo.tsx
  client/src/pages/main-page/hooks/useToppingDetail.tsx
  client/src/pages/main-page/hooks/useToppingList.tsx
Labels: 🖥 Frontend, ❗️high-priority, 🔨 Feature

#175 feature/#168 Intro 페이지 기초 디자인
  client/package.json
  client/src/App.tsx
  client/src/assets/images/index.tsx
  client/src/assets/images/pixel_bingsu.png
  client/src/pages/index.tsx
  client/src/pages/intro-page/IntroPage.tsx
  client/src/pages/intro-page/IntroPageStyle.tsx
  client/src/pages/intro-page/index.ts
Labels: 🖥 Frontend, ❗️high-priority, 🔨 Feature

#178 feature/#176 페이지네이션 버그 수정
  client/src/pages/main-page/MainPage.tsx
Labels: 🐛 Bug, 🖥 Frontend, ❗️high-priority

#179 feature#177 로그인 되어있으면 해당 계정 빙수로 redirect
  client/src/common/utils/generateRandomName.ts
  client/src/pages/intro-page/IntroPage.tsx
Labels: 🖥 Frontend, 🔨 Feature, ↔️ mid-priority

#182 feature/#174 readme 추가
  README.md
Labels: 📖 Document

#184 feature/#181 로그인되어 있으면 빙수로 redirect
  client/public/index.html
  client/src/pages/login-page/LoginPage.tsx
  client/src/pages/login-page/hook/useLogin.ts
Labels: 🖥 Frontend, ↔️ mid-priority, 🔧 enhancement

#186 feature/#185 Refresh/Access Token 인증시간 수정
  server/src/middlewares/AuthJWT.ts
  server/src/services/UserService.ts
Labels: ⚙️ Backend, ⬇️ low-priority, 🔧 enhancement

#191 feature/#188 mail style 수정
  server/src/services/MailService.ts
Labels: ⚙️ Backend, 🔧 enhancement

#198 feature/#196 로그인, 회원가입 페이지 스크롤 방지 추가
  client/src/pages/login-page/LoginPage.tsx
  client/src/pages/login-page/LoginPageStyle.tsx
  client/src/pages/register-page/RegisterPage.tsx
  client/src/pages/register-page/RegisterPageStyle.tsx
Labels: 🖥 Frontend, ❗️high-priority, 🔧 enhancement

#200 feature/#199 회원가입 폼 비밀번호 확인 추가
  client/src/common/components/form-component/CustomForm.tsx
  client/src/common/components/form-component/CustomFormStyle.tsx
  client/src/pages/register-page/components/RegisterForm.tsx
  client/src/types/interfaces.ts
Labels: 🖥 Frontend, ❗️high-priority, 🔨 Feature

#202 feature/#201 상세페이지 종료 애니메이션
  client/src/pages/main-page/MainPage.tsx
  client/src/pages/main-page/components/Detail.tsx
  client/src/pages/main-page/components/DetailStyle.tsx
Labels: 🖥 Frontend, 🔨 Feature, ⬇️ low-priority

#211 [#210] feat : 커스텀 모달 적용
  client/src/common/components/Modal.tsx
  client/src/common/hooks/useLogout.tsx
  client/src/pages/main-page/MainPage.tsx
  client/src/pages/main-page/components/Header.tsx
Labels: 🖥 Frontend, 🔨 Feature, ↔️ mid-priority

#214 feature/#213 모달 스크롤 제거
  client/src/common/components/Modal.tsx
Labels: 🖥 Frontend, ⬇️ low-priority, 🔧 enhancement

#216 Feature/#212 env 설정
  .gitignore
  client/.env
  client/package-lock.json
  client/package.json
  client/src/common/hooks/useLogout.tsx
  client/src/pages/intro-page/IntroPage.tsx
  client/src/pages/login-page/hook/useLogin.ts
  client/src/pages/main-page/hooks/useInfo.tsx
  client/src/pages/main-page/hooks/useShareMyLink.tsx
  client/src/pages/main-page/hooks/useToppingDetail.tsx
  client/src/pages/main-page/hooks/useToppingList.tsx
  client/src/pages/register-page/hook/useRegister.ts
  client/src/pages/write-page/hook/useWrite.ts
  client/src/types/node.d.ts
  client/tsconfig.json
  client/webpack.config.js
Labels: 🖥 Frontend, ❗️high-priority, 🔨 Feature, 🔧 enhancement

#222 feature/#221 Github OAuth 버튼 비활성화
  client/src/pages/login-page/LoginPageStyle.tsx
  client/src/pages/login-page/components/GithubOAuth.tsx
  client/src/pages/login-page/components/GithubOAuthStyle.tsx
  client/src/pages/write-page/components/ArticleForm.tsx
  client/src/pages/write-page/components/ArticleFormStyle.tsx
  client/src/pages/write-page/components/SelectTopingStyle.tsx
Labels: 🖥 Frontend, ❗️high-priority, 🔧 enhancement
